services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        ENVIRONMENT: development
    image: "${COMPOSE_PROJECT_NAME:-smartsheet}_dev"
    ports:
      - "8000:8000"
    command: dev
    entrypoint: /entrypoint
    volumes:
      - ./src:/opt/project/src:cached
      - /opt/project/src/.venv
    env_file:
      - ./.env

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    image: "${COMPOSE_PROJECT_NAME:-smartsheet}_dev_frontend"
    command: npm run dev
    volumes:
      - ./src/frontend:/opt/project/src/frontend:cached
      - /opt/project/src/frontend/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_DEV_SERVER_HOST=${VITE_DEV_SERVER_HOST:-localhost}
    depends_on:
      - django
