# Generated by Django 5.2.10 on 2026-01-28 15:29

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='smartsheet_token',
            field=core.fields.EncryptedCharField(blank=True, default='', max_length=512),
        ),
    ]
